import type { Tool, ToolAnnotations } from "@modelcontextprotocol/sdk/types.js";

export type RequiredToolHints = Pick<
  Required<ToolAnnotations>,
  "readOnlyHint" | "destructiveHint" | "openWorldHint"
>;

export const READ_ONLY_TOOL_NAMES = new Set([
  "get_account",
  "get_app_urls",
  "get_company",
  "get_sync_rules",
  "get_shopify_automation_settings",
  "list_api_keys",
  "list_websites",
  "check_website",
  "get_integration_guide",
  "get_subscriber",
  "get_subscriber_import",
  "list_subscriber_notes",
  "search_subscribers",
  "list_products",
  "list_tags",
  "list_lists",
  "list_segments",
  "get_segment_count",
  "list_audience_syncs",
  "list_ad_accounts",
  "list_templates",
  "get_template",
  "list_ab_tests",
  "get_ab_test",
  "get_ab_test_stats",
  "list_campaigns",
  "get_campaign",
  "get_email_send",
  "list_forms",
  "get_form_embed",
  "get_recipient_suppression",
  "list_landing_pages",
  "get_landing_page",
  "list_sequences",
  "get_sequence",
  "list_transactional_emails",
  "get_transactional_email",
  "get_stats",
  "get_campaign_stats",
  "get_sequence_stats",
  "list_campaign_events",
  "list_sequence_events",
  "get_subscriber_activity",
  "list_team_members",
  "list_conversations",
  "get_conversation",
  "list_webhooks",
  "list_webhook_deliveries",
  "generate_email",
  "generate_subject_lines",
  "generate_sms",
  "get_sms_settings",
]);

export const MUTATING_TOOL_NAMES = new Set([
  "select_company",
  "create_company",
  "update_company",
  "update_sync_rules",
  "update_shopify_automation_settings",
  "create_api_key",
  "revoke_api_key",
  "delete_api_key",
  "add_sending_domain",
  "add_website",
  "verify_sending_domain",
  "add_subscriber",
  "create_subscriber_import",
  "update_subscriber",
  "add_subscriber_note",
  "remove_subscriber",
  "delete_subscriber_note",
  "upsert_products",
  "delete_product",
  "attach_product_file",
  "remove_product_file",
  "upload_image_asset",
  "sync_products",
  "create_tag",
  "update_tag",
  "delete_tag",
  "create_list",
  "update_list",
  "delete_list",
  "add_subscribers_to_list",
  "remove_subscribers_from_list",
  "create_segment",
  "update_segment",
  "delete_segment",
  "create_audience_sync",
  "update_audience_sync",
  "delete_audience_sync",
  "sync_audience_now",
  "create_template",
  "update_template",
  "set_template_localization",
  "sync_template_localizations",
  "delete_template",
  "restart_ab_test",
  "update_ab_test_variant",
  "create_ab_test",
  "add_ab_test_variant",
  "delete_ab_test_variant",
  "delete_ab_test",
  "create_campaign",
  "update_campaign",
  "schedule_campaign",
  "send_test_email",
  "send_test_sms",
  "cancel_campaign",
  "pause_campaign",
  "resume_campaign",
  "delete_campaign",
  "duplicate_campaign",
  "resend_campaign_to_non_openers",
  "create_form",
  "create_landing_page",
  "update_landing_page",
  "delete_landing_page",
  "publish_landing_page",
  "unpublish_landing_page",
  "connect_landing_page_domain",
  "update_landing_page_domain_settings",
  "create_sequence",
  "generate_sequence",
  "update_sequence",
  "update_sequence_node",
  "update_sequence_nodes",
  "edit_sequence_graph",
  "insert_sequence_step",
  "enable_sequence",
  "disable_sequence",
  "pause_sequence_enrollments",
  "resume_sequence_enrollments",
  "enroll_subscribers_in_sequence",
  "cancel_sequence_enrollments",
  "delete_sequence",
  "create_transactional_email",
  "update_transactional_email",
  "send_email",
  "invite_team_member",
  "cancel_team_invitation",
  "reply_to_conversation",
  "update_conversation_status",
  "mark_conversation_read",
  "create_webhook",
  "update_webhook",
  "delete_webhook",
  "test_webhook",
  "replay_webhook_delivery",
  "submit_feedback",
  "remove_recipient_suppression",
]);

export const OPEN_WORLD_TOOL_NAMES = new Set([
  "send_test_email",
  "send_test_sms",
  "schedule_campaign",
  "resume_campaign",
  "publish_landing_page",
  "connect_landing_page_domain",
  "update_landing_page_domain_settings",
  "add_sending_domain",
  "add_website",
  "verify_sending_domain",
  "enable_sequence",
  "resume_sequence_enrollments",
  "send_email",
  "invite_team_member",
  "reply_to_conversation",
  "create_webhook",
  "update_webhook",
  "test_webhook",
  "replay_webhook_delivery",
  "remove_recipient_suppression",
]);

export const DESTRUCTIVE_TOOL_NAMES = new Set([
  "revoke_api_key",
  "delete_api_key",
  "remove_subscriber",
  "delete_subscriber_note",
  "delete_product",
  "remove_product_file",
  "delete_tag",
  "delete_list",
  "remove_subscribers_from_list",
  "delete_segment",
  "delete_audience_sync",
  "delete_template",
  "restart_ab_test",
  "delete_ab_test_variant",
  "delete_ab_test",
  "cancel_campaign",
  "delete_campaign",
  "delete_landing_page",
  "unpublish_landing_page",
  "disable_sequence",
  "edit_sequence_graph",
  "cancel_sequence_enrollments",
  "delete_sequence",
  "cancel_team_invitation",
  "delete_webhook",
  "remove_recipient_suppression",
]);

export function getRequiredToolHints(toolName: string): RequiredToolHints {
  const isReadOnly = READ_ONLY_TOOL_NAMES.has(toolName);
  const isMutating = MUTATING_TOOL_NAMES.has(toolName);

  if (isReadOnly === isMutating) {
    throw new Error(
      `MCP tool "${toolName}" must be classified as exactly one of read-only or mutating.`
    );
  }

  return {
    readOnlyHint: isReadOnly,
    destructiveHint: isReadOnly ? false : DESTRUCTIVE_TOOL_NAMES.has(toolName),
    openWorldHint: OPEN_WORLD_TOOL_NAMES.has(toolName),
  };
}

export function withRequiredToolHints(tool: Tool): Tool {
  return {
    ...tool,
    annotations: {
      ...tool.annotations,
      ...getRequiredToolHints(tool.name),
    },
  };
}
