import type { Tool, ToolAnnotations } from "../mcp-types.js";

export type RequiredToolHints = Pick<
  Required<ToolAnnotations>,
  "readOnlyHint" | "destructiveHint" | "openWorldHint"
>;

export const READ_ONLY_TOOL_NAMES = new Set([
  "get_account",
  "get_app_urls",
  "get_company",
  "get_sync_rules",
  "get_shopify_automation_settings",
  "list_api_keys",
  // Builds a dashboard link and nothing else: no key is created, changed, or
  // returned until the owner confirms in their own browser session.
  "request_api_key_handoff",
  "list_websites",
  "list_integrations",
  "get_integration",
  "get_integration_pixel",
  "list_web_tracking_keys",
  "get_web_tracking_key",
  "list_integration_capabilities",
  "list_integration_activity",
  "get_event_schema",
  "get_email_block_schema",
  "list_sender_profiles",
  "get_notification_preferences",
  "get_tracking_settings",
  "get_email_design_system",
  "get_sending_status",
  "check_website",
  "get_integration_guide",
  "get_subscriber",
  "get_subscriber_import",
  "list_subscriber_notes",
  "search_subscribers",
  "list_products",
  "list_tags",
  "list_lists",
  "list_segments",
  "get_segment_count",
  "list_audience_syncs",
  "list_ad_accounts",
  "list_templates",
  "get_template",
  "list_email_components",
  "get_email_component",
  "get_default_email_component",
  "list_ab_tests",
  "get_ab_test",
  "get_ab_test_stats",
  "list_campaigns",
  "get_campaign",
  "get_campaign_audience",
  "list_campaign_goals",
  // Returns HTML and never mutates or sends, despite being backed by a POST.
  "render_email",
  "list_email_sends",
  "get_email_send",
  "list_forms",
  "get_form_embed",
  "list_popups",
  "get_popup",
  "get_popup_embed",
  "get_recipient_suppression",
  "list_recipient_suppressions",
  "list_landing_pages",
  "get_landing_page",
  "render_landing_page",
  "list_sequences",
  "get_sequence",
  "simulate_sequence",
  "list_sequence_enrollments",
  "get_sequence_enrollment_realignment",
  "list_sequence_goals",
  "get_sequence_inbound_webhook",
  "list_transactional_emails",
  "get_transactional_email",
  "get_stats",
  "get_transactional_stats",
  "get_campaign_stats",
  "list_poll_responses",
  "get_sequence_stats",
  "list_campaign_events",
  "list_sequence_events",
  "list_email_metrics",
  "get_subscriber_activity",
  "list_team_members",
  "list_conversations",
  "get_conversation",
  "list_webhooks",
  "list_webhook_deliveries",
  "generate_email",
  "generate_subject_lines",
  "generate_sms",
  "get_sms_settings",
  "get_sms_usage",
]);

export const MUTATING_TOOL_NAMES = new Set([
  "select_company",
  "create_company",
  "update_company",
  "update_notification_preferences",
  "update_sender_profile",
  "update_tracking_settings",
  "update_email_design_system",
  "update_sms_number_label",
  "release_sms_number",
  "resume_sending",
  "update_sync_rules",
  "update_shopify_automation_settings",
  "connect_integration",
  "set_integration_sync_enabled",
  "set_integration_list_targeting",
  "sync_integration",
  // Writes a web pixel to the merchant's Shopify store.
  "activate_integration_pixel",
  "create_web_tracking_key",
  "update_web_tracking_key",
  "delete_web_tracking_key",
  "create_api_key",
  "update_api_key",
  "revoke_api_key",
  "delete_api_key",
  "add_sending_domain",
  "add_website",
  "verify_sending_domain",
  "add_subscriber",
  "create_subscriber_import",
  "update_subscriber",
  "add_subscriber_note",
  "remove_subscriber",
  "delete_subscriber_note",
  "trigger_subscriber_event",
  "trigger_subscriber_events",
  "import_subscriber_events",
  "bulk_add_subscriber_tags",
  "bulk_remove_subscriber_tags",
  "upsert_products",
  "delete_product",
  "attach_product_file",
  "remove_product_file",
  "upload_image_asset",
  "sync_products",
  "create_tag",
  "update_tag",
  "delete_tag",
  "create_list",
  "update_list",
  "delete_list",
  "add_subscribers_to_list",
  "remove_subscribers_from_list",
  "create_segment",
  "update_segment",
  "delete_segment",
  "create_audience_sync",
  "update_audience_sync",
  "delete_audience_sync",
  "sync_audience_now",
  "create_template",
  "update_template",
  "set_template_localization",
  "sync_template_localizations",
  "delete_template",
  "create_email_component",
  "update_email_component",
  "set_default_email_component",
  "delete_email_component",
  "restart_ab_test",
  "select_ab_test_winner",
  "update_ab_test_variant",
  "update_ab_test",
  "create_ab_test",
  "add_ab_test_variant",
  "delete_ab_test_variant",
  "delete_ab_test",
  "create_campaign",
  "update_campaign",
  "schedule_campaign",
  "send_test_email",
  "send_test_sms",
  "share_campaign",
  "unshare_campaign",
  "share_template",
  "unshare_template",
  "unschedule_campaign",
  "cancel_campaign",
  "pause_campaign",
  "resume_campaign",
  "delete_campaign",
  "duplicate_campaign",
  "resend_campaign_to_non_openers",
  "create_form",
  "update_form",
  "create_popup",
  "update_popup",
  "duplicate_popup",
  "delete_popup",
  "create_landing_page",
  "update_landing_page",
  "duplicate_landing_page",
  "delete_landing_page",
  "publish_landing_page",
  "unpublish_landing_page",
  "connect_landing_page_domain",
  "update_landing_page_domain_settings",
  "remove_landing_page_domain",
  "create_sequence",
  "generate_sequence",
  "send_sequence_test_email",
  "update_sequence",
  "update_sequence_node",
  "update_sequence_nodes",
  "edit_sequence_graph",
  "insert_sequence_step",
  "enable_sequence",
  "disable_sequence",
  "duplicate_sequence",
  "archive_sequence",
  "unarchive_sequence",
  "create_campaign_goal",
  "update_campaign_goal",
  "delete_campaign_goal",
  "create_sequence_goal",
  "update_sequence_goal",
  "delete_sequence_goal",
  "configure_sequence_inbound_webhook",
  "rotate_sequence_inbound_webhook_secret",
  "pause_sequence_enrollments",
  "resume_sequence_enrollments",
  "enroll_subscribers_in_sequence",
  "cancel_sequence_enrollments",
  "move_sequence_enrollments",
  "realign_sequence_enrollments",
  "delete_sequence",
  "create_transactional_email",
  "update_transactional_email",
  "delete_transactional_email",
  "send_email",
  "invite_team_member",
  "cancel_team_invitation",
  "reply_to_conversation",
  "update_conversation_status",
  "mark_conversation_read",
  "create_webhook",
  "update_webhook",
  "delete_webhook",
  "test_webhook",
  "replay_webhook_delivery",
  "submit_feedback",
  "remove_recipient_suppression",
]);

export const OPEN_WORLD_TOOL_NAMES = new Set([
  "send_test_email",
  "send_test_sms",
  "send_sequence_test_email",
  "schedule_campaign",
  "resume_campaign",
  "publish_landing_page",
  "connect_landing_page_domain",
  "update_landing_page_domain_settings",
  "remove_landing_page_domain",
  "add_sending_domain",
  "add_website",
  "verify_sending_domain",
  // Validates credentials against the provider's API and queues backfills.
  "connect_integration",
  // Reaches the provider's API (payment provider, Supabase) through a
  // background sync job.
  "sync_integration",
  // Both talk to the Shopify Admin API in the request: the read cannot be
  // served from our own state, and the write changes the merchant's store.
  "get_integration_pixel",
  "activate_integration_pixel",
  "enable_sequence",
  "unarchive_sequence",
  "resume_sequence_enrollments",
  // Releases contacts onto a live step, so the sequence starts sending to them
  // as soon as the worker picks them up.
  "move_sequence_enrollments",
  "send_email",
  "select_ab_test_winner",
  "invite_team_member",
  "reply_to_conversation",
  "create_webhook",
  "update_webhook",
  "test_webhook",
  "replay_webhook_delivery",
  "remove_recipient_suppression",
]);

export const DESTRUCTIVE_TOOL_NAMES = new Set([
  "revoke_api_key",
  "delete_api_key",
  "remove_subscriber",
  "delete_subscriber_note",
  "delete_product",
  "delete_web_tracking_key",
  "remove_product_file",
  "delete_tag",
  "delete_list",
  "remove_subscribers_from_list",
  "bulk_remove_subscriber_tags",
  "delete_segment",
  "delete_audience_sync",
  "delete_template",
  // Deleting the pinned default footer makes new emails fall back to the
  // generated footer, so it changes what future sends look like.
  "delete_email_component",
  "restart_ab_test",
  "delete_ab_test_variant",
  "delete_ab_test",
  "cancel_campaign",
  "delete_campaign",
  "delete_landing_page",
  "remove_landing_page_domain",
  "unpublish_landing_page",
  "delete_popup",
  // Disabling sync stops an integration feeding the account, in the same way
  // disabling a sequence stops it running. Reversible, but worth a confirm.
  "set_integration_sync_enabled",
  // Retargeting changes which lists an integration's future contacts join, so
  // it silently changes who gets mailed. Reversible, but contacts created
  // under the old targeting are not retroactively moved - worth a confirm.
  "set_integration_list_targeting",
  "disable_sequence",
  "archive_sequence",
  "delete_campaign_goal",
  "delete_sequence_goal",
  "rotate_sequence_inbound_webhook_secret",
  "edit_sequence_graph",
  "cancel_sequence_enrollments",
  // Not reversible in the way that matters: a released contact can receive the
  // target step's email before anyone notices the batch was wrong.
  "move_sequence_enrollments",
  "realign_sequence_enrollments",
  "delete_sequence",
  "cancel_team_invitation",
  "delete_webhook",
  "delete_transactional_email",
  "remove_recipient_suppression",
  // Re-sharing mints a different URL, so every copy of the old link that was
  // already passed around is permanently dead.
  "unshare_campaign",
  "unshare_template",
  // Hands the number back to the carrier - it cannot be recovered, and any
  // campaign/sequence step still pinned to it starts skipping instead of
  // sending.
  "release_sms_number",
]);

export function getRequiredToolHints(toolName: string): RequiredToolHints {
  const isReadOnly = READ_ONLY_TOOL_NAMES.has(toolName);
  const isMutating = MUTATING_TOOL_NAMES.has(toolName);

  if (isReadOnly === isMutating) {
    throw new Error(
      `MCP tool "${toolName}" must be classified as exactly one of read-only or mutating.`
    );
  }

  return {
    readOnlyHint: isReadOnly,
    destructiveHint: isReadOnly ? false : DESTRUCTIVE_TOOL_NAMES.has(toolName),
    openWorldHint: OPEN_WORLD_TOOL_NAMES.has(toolName),
  };
}

const TOOL_TITLE_ACRONYMS: Record<string, string> = {
  ab: "A/B",
  ai: "AI",
  api: "API",
  html: "HTML",
  id: "ID",
  mcp: "MCP",
  nps: "NPS",
  sms: "SMS",
  url: "URL",
  urls: "URLs",
  utm: "UTM",
};

function getToolTitle(toolName: string): string {
  return toolName
    .split("_")
    .filter(Boolean)
    .map(
      (part) =>
        TOOL_TITLE_ACRONYMS[part] ??
        part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join(" ");
}

export function withRequiredToolHints(tool: Tool): Tool {
  return {
    ...tool,
    annotations: {
      ...tool.annotations,
      title: tool.annotations?.title ?? getToolTitle(tool.name),
      ...getRequiredToolHints(tool.name),
    },
  };
}
